/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./src/components/base/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/base/BaseHeader.vue')['default']
    BaseLayout: typeof import('./src/components/base/BaseLayout.vue')['default']
    BasePopup: typeof import('./src/components/base/BasePopup.vue')['default']
    BillsTable: typeof import('./src/components/widgets/BillsTable.vue')['default']
    ChangeTariffPopup: typeof import('./src/components/layouts/ChangeTariffPopup.vue')['default']
    CreateBillPopup: typeof import('./src/components/layouts/CreateBillPopup.vue')['default']
    LayoutWrapper: typeof import('./src/components/base/BaseLayout.vue')['default']
    MakeSureDelete: typeof import('./src/components/layouts/MakeSureDelete.vue')['default']
    NavBar: typeof import('./src/components/widgets/NavBar.vue')['default']
    PopupWrapper: typeof import('./src/components/layouts/PopupWrapper.vue')['default']
    ResidentActionPopup: typeof import('./src/components/layouts/ResidentCreatePopup.vue')['default']
    ResidentCreatePopup: typeof import('./src/components/layouts/ResidentCreatePopup.vue')['default']
    ResidentsTable: typeof import('./src/components/widgets/ResidentsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/widgets/SideBar.vue')['default']
  }
}
